-- SOL 1
SELECT  CART_ID
FROM    CART_PRODUCTS
WHERE   1=1
AND     (NAME = 'Milk' OR NAME = 'Yogurt')
GROUP BY CART_ID
HAVING  COUNT(DISTINCT CART_ID, NAME) > 1
ORDER BY CART_ID;

-- SOL 2
SELECT      DISTINCT(a.CART_ID)
FROM        CART_PRODUCTS a, CART_PRODUCTS b
WHERE       a.NAME = 'Milk' and b.NAME = 'Yogurt' and a.CART_ID = b.CART_ID
ORDER BY    a.CART_ID