SELECT  A.ANIMAL_ID, A.ANIMAL_TYPE, A.NAME
FROM    ANIMAL_INS A
JOIN    ANIMAL_OUTS B USING(ANIMAL_ID)
WHERE   1=1
AND     A.SEX_UPON_INTAKE LIKE '%Intact%'
AND     (B.SEX_UPON_OUTCOME LIKE '%Spayed%' OR B.SEX_UPON_OUTCOME LIKE '%Neutered%')
ORDER BY ANIMAL_ID
;
