SELECT  CAST(DATE_FORMAT(A.START_DATE,'%m') AS UNSIGNED) AS MONTH,
        CAR_ID,
        COUNT(HISTORY_ID) AS RECORDS
FROM    CAR_RENTAL_COMPANY_RENTAL_HISTORY A
WHERE   1=1
AND     DATE_FORMAT(A.START_DATE,'%Y-%m-%d') BETWEEN '2022-08-01' AND '2022-10-31'
AND     5 <=      (SELECT   COUNT(B.HISTORY_ID)
                   FROM     CAR_RENTAL_COMPANY_RENTAL_HISTORY B
                   WHERE    1=1
                   AND      DATE_FORMAT(B.START_DATE,'%Y-%m-%d') BETWEEN '2022-08-01' AND '2022-10-31'
                   AND      A.CAR_ID = B.CAR_ID)
GROUP BY MONTH, CAR_ID
HAVING RECORDS > 0
ORDER BY MONTH ASC, CAR_ID DESC