SELECT  USER_ID, 
        NICKNAME,
        CONCAT(A.CITY,' ',A.STREET_ADDRESS1, ' ', A.STREET_ADDRESS2) AS 전체주소,
        CONCAT(SUBSTR(A.TLNO,1,3),'-',SUBSTR(A.TLNO,4,4),'-',SUBSTR(A.TLNO,8,4)) AS 전화번호
FROM    USED_GOODS_USER A
WHERE   1=1
AND     3 <=    (SELECT COUNT(*)
                 FROM   USED_GOODS_BOARD B
                 WHERE  1=1
                 AND    A.USER_ID = B.WRITER_ID)
ORDER BY USER_ID DESC;