SELECT  CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM    (SELECT  CATEGORY,
                 PRODUCT_NAME,
                 PRICE,
                 RANK() OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) AS RNUM
         FROM    FOOD_PRODUCT) AS RK
WHERE   1=1
AND     RK.RNUM = 1
AND     CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY MAX_PRICE DESC
;
