SELECT  MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
FROM    MEMBER_PROFILE A
JOIN    REST_REVIEW B USING(MEMBER_ID)
WHERE   1=1
AND     MEMBER_ID = (SELECT C.MEMBER_ID
                     FROM   REST_REVIEW C
                     WHERE  1=1
                     GROUP BY C.MEMBER_ID
                     ORDER BY COUNT(REVIEW_ID) DESC
                     LIMIT 1)
ORDER BY REVIEW_DATE, REVIEW_TEXT