SELECT  A.CATEGORY AS CATEGORY, SUM(B.SALES) AS TOTAL_SALES
FROM    BOOK A
JOIN    BOOK_SALES B USING(BOOK_ID)
WHERE   1=1
AND     B.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY A.CATEGORY
ORDER BY A.CATEGORY
;