SELECT  C.AUTHOR_ID, C.AUTHOR_NAME, B.CATEGORY,
        SUM(B.PRICE*A.SALES) AS TOTAL_SALES
FROM    BOOK_SALES A
JOIN    BOOK B USING(BOOK_ID)
JOIN    AUTHOR C USING(AUTHOR_ID)
WHERE   1=1
AND     DATE_FORMAT(A.SALES_DATE,'%Y-%m') = '2022-01' 
GROUP BY B.AUTHOR_ID, B.CATEGORY
ORDER BY B.AUTHOR_ID ASC, B.CATEGORY DESC