SELECT  DISTINCT CAR_ID
FROM    CAR_RENTAL_COMPANY_CAR A
JOIN    CAR_RENTAL_COMPANY_RENTAL_HISTORY B USING(CAR_ID)
WHERE   1=1
AND     A.CAR_TYPE = '세단'
AND     B.START_DATE BETWEEN '2022-10-01' AND '2022-10-31'
ORDER BY CAR_ID DESC
;