SELECT  REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE),2) AS SCORE
FROM    REST_INFO A
JOIN    REST_REVIEW B USING(REST_ID)
WHERE   1=1
AND     ADDRESS LIKE '서울%'
GROUP BY REST_ID
ORDER BY SCORE DESC, FAVORITES DESC
;